In [1]:
import numpy as np
from rnn_utils import *

In [4]:
def rnn_cell_forward(xt,a_prev,parameters):
    Wax = parameters["Wax"]
    Waa = parameters["Waa"]
    Wya = parameters["Wya"]
    ba = parameters["ba"]
    by = parameters["by"]
    
    a_next = np.tanh(np.dot(Waa,a_prev)+np.dot(Wax,xt)+ba)
    yt_pred = softmax(np.dot(Wya,a_next)+by)
    
    cache = (a_next, a_prev, xt, parameters)
    
    return a_next,yt_pred,cache

In [5]:
np.random.seed(1)
xt_tmp = np.random.randn(3,10)
a_prev_tmp = np.random.randn(5,10)
parameters_tmp = {}
parameters_tmp['Waa'] = np.random.randn(5,5)
parameters_tmp['Wax'] = np.random.randn(5,3)
parameters_tmp['Wya'] = np.random.randn(2,5)
parameters_tmp['ba'] = np.random.randn(5,1)
parameters_tmp['by'] = np.random.randn(2,1)

a_next_tmp, yt_pred_tmp, cache_tmp = rnn_cell_forward(xt_tmp, a_prev_tmp, parameters_tmp)
print("a_next[4] = \n", a_next_tmp[4])
print("a_next.shape = \n", a_next_tmp.shape)
print("yt_pred[1] =\n", yt_pred_tmp[1])
print("yt_pred.shape = \n", yt_pred_tmp.shape)

a_next[4] = 
 [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape = 
 (5, 10)
yt_pred[1] =
 [0.9888161  0.01682021 0.21140899 0.36817467 0.98988387 0.88945212
 0.36920224 0.9966312  0.9982559  0.17746526]
yt_pred.shape = 
 (2, 10)


In [13]:
np.random.randn(3,10)

array([[-0.08601853, -0.14813658,  0.13912627, -1.90290863,  2.33014207,
        -0.30626553, -1.45606357, -2.07490519, -0.24545321,  0.002979  ],
       [-0.26774635, -0.40378174,  0.1572718 ,  0.33893515, -1.10423149,
         0.7030659 , -0.32545971, -0.63974777,  0.65757628,  0.61619104],
       [-1.0237667 ,  0.03685261, -1.22278943, -0.98510142,  1.1183585 ,
        -0.73695489, -0.18820403, -1.21377262,  0.50470015, -1.4922319 ]])

In [17]:
def rnn_forward(x, a0, parameters):
    caches = []
    
    n_x,m,T_x = x.shape
    n_y,n_a = parameters["Wya"].shape
    
    a = np.zeros((n_a,m,T_x))
    y_pred = np.zeros((n_y,m,T_x))
    
    a_next = a0
    
    for t in range (T_x):
        
        a_next, yt_pred, cache = rnn_cell_forward(x[:,:,t], a_next, parameters)
        a[:,:,t] = a_next
        y_pred[:,:,t] = yt_pred
        caches.append(cache)
        
    caches = (caches, x)
    
    return a, y_pred, caches
        

In [18]:
np.random.seed(1)
x = np.random.randn(3,10,4)
a0 = np.random.randn(5,10)
Waa = np.random.randn(5,5)
Wax = np.random.randn(5,3)
Wya = np.random.randn(2,5)
ba = np.random.randn(5,1)
by = np.random.randn(2,1)
parameters = {"Waa": Waa, "Wax": Wax, "Wya": Wya, "ba": ba, "by": by}

a, y_pred, caches = rnn_forward(x, a0, parameters)
print("a[4][1] = ", a[4][1])
print("a.shape = ", a.shape)
print("y_pred[1][3] =", y_pred[1][3])
print("y_pred.shape = ", y_pred.shape)
print("caches[1][1][3] =", caches[1][1][3])
print("len(caches) = ", len(caches))

a[4][1] =  [-0.99999375  0.77911235 -0.99861469 -0.99833267]
a.shape =  (5, 10, 4)
y_pred[1][3] = [0.79560373 0.86224861 0.11118257 0.81515947]
y_pred.shape =  (2, 10, 4)
caches[1][1][3] = [-1.1425182  -0.34934272 -0.20889423  0.58662319]
len(caches) =  2


In [26]:
y_pred

array([[[9.99129368e-01, 8.90772592e-01, 7.04206315e-01, 9.19730000e-01],
        [9.99394165e-01, 3.26947813e-01, 9.98789616e-01, 9.88219303e-01],
        [9.94277463e-01, 9.95999371e-01, 9.97939529e-01, 2.76624090e-01],
        [2.04396268e-01, 1.37751394e-01, 8.88817431e-01, 1.84840534e-01],
        [7.42084036e-01, 4.16030656e-01, 5.96207274e-02, 9.56452021e-01],
        [3.43688280e-01, 9.98867515e-01, 9.89766361e-01, 8.99137589e-01],
        [9.39252776e-01, 7.07585502e-01, 8.85151052e-01, 3.34768716e-01],
        [9.35504646e-01, 9.85731426e-01, 9.37994449e-01, 6.45782938e-01],
        [6.39183022e-01, 2.35008185e-02, 8.20174082e-01, 3.42431253e-01],
        [6.07750160e-01, 8.98666718e-01, 9.99114486e-01, 9.90187623e-01]],

       [[8.70631878e-04, 1.09227408e-01, 2.95793685e-01, 8.02699998e-02],
        [6.05834882e-04, 6.73052187e-01, 1.21038427e-03, 1.17806974e-02],
        [5.72253732e-03, 4.00062909e-03, 2.06047094e-03, 7.23375910e-01],
        [7.95603732e-01, 8.62248606e

In [19]:
x = np.random.randn(3,10,4)

In [23]:
x[:,:,2]

array([[-0.20339445,  1.79215821, -0.66575452, -0.31098498,  0.67471153,
        -1.30572692,  1.93752881,  0.585662  , -1.52568032,  1.20205486],
       [-0.7332716 ,  0.88490881,  1.23225307, -0.43750898,  0.21112476,
         0.0809271 , -0.68067814,  0.78477065, -1.47115693,  1.62284909],
       [-0.59980453, -0.66134424, -0.05118845, -0.79726979,  0.9561217 ,
         1.15528789, -0.10679399, -1.94258918,  1.27852808,  0.00854895]])

In [21]:
x

array([[[-1.98837863e-01, -7.00398505e-01, -2.03394449e-01,
          2.42669441e-01],
        [ 2.01830179e-01,  6.61020288e-01,  1.79215821e+00,
         -1.20464572e-01],
        [-1.23312074e+00, -1.18231813e+00, -6.65754518e-01,
         -1.67419581e+00],
        [ 8.25029824e-01, -4.98213564e-01, -3.10984978e-01,
         -1.89148284e-03],
        [-1.39662042e+00, -8.61316361e-01,  6.74711526e-01,
          6.18539131e-01],
        [-4.43171931e-01,  1.81053491e+00, -1.30572692e+00,
         -3.44987210e-01],
        [-2.30839743e-01, -2.79308500e+00,  1.93752881e+00,
          3.66332015e-01],
        [-1.04458938e+00,  2.05117344e+00,  5.85662000e-01,
          4.29526140e-01],
        [-6.06998398e-01,  1.06222724e-01, -1.52568032e+00,
          7.95026094e-01],
        [-3.74438319e-01,  1.34048197e-01,  1.20205486e+00,
          2.84748111e-01]],

       [[ 2.62467445e-01,  2.76499305e-01, -7.33271604e-01,
          8.36004719e-01],
        [ 1.54335911e+00,  7.58805660e-01