Source:
https://www.youtube.com/watch?v=ZB7BZMhfPgk

In [1]:
# world without Numpy
a = [1,2,3,4]
b= [4,5,6,7]
a+b

[1, 2, 3, 4, 4, 5, 6, 7]

In [2]:
res = []
for first,second in zip(a,b):
    res.append(first+second)
print(res)

[5, 7, 9, 11]


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
a.size

4

In [9]:
#universal func ufunc
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Indexing and slicing

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [12]:
#get last three items
a[-3:]

array([ 8,  9, 10])

In [13]:
#grab first three elements
a[:3]

array([1, 2, 3])

In [14]:
a = np.arange(25).reshape(5,5)

In [15]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [18]:
a[1::2,0:4:2]

array([[ 5,  7],
       [15, 17]])

In [19]:
a[4]

array([20, 21, 22, 23, 24])